#pragma once

// Constant-velocity FlexPWM stepper driver for Teensy 4.x.
//
// Replaces AccelStepper's loop()-polled runSpeed() / run() pattern with
// hardware-timed pulses generated by a FlexPWM submodule. Step counting
// happens in the submodule's reload-interrupt ISR (one IRQ per pulse)
// at interrupt priority — immune to anything that blocks the main loop
// (Serial flushes, EEPROM writes, Ethernet flush/stop, HTTP request
// handlers). This is the bench-scoped realisation of CLAUDE.md's
// "Firmware portability rule": no AccelStepper-style runSpeed polling
// in the tuner controller's pulse path.
//
// No acceleration ramp — motor jumps instantly to the commanded rate.
// Fine for typical tuner speeds (≤ 2000 steps/s); a software ramp
// can be layered on later if higher speeds need it. See
// docs/HW-T41-PINMAP.md §1 for the two viable architectures
// (FlexPWM-direct vs PIT+ISR) and which pins support which.
//
// STEP pin MUST be FlexPWM-capable on a distinct submodule per axis
// (X→FlexPWM4.2A, Y→FlexPWM2.0A on this bench — see HW-T41-PINMAP.md
// table in §1). DIR pin is any GPIO. Driver-enable (EN) handling is
// outside this class — main.cpp keeps the existing release-on-idle
// behaviour around `ensureDriverReady` / `releaseDriverForIdle`.

#include <Arduino.h>
#include <imxrt.h>

class FlexPwmStepper {
public:
    // pwm + submodule + irq identify the FlexPWM unit driving stepPin.
    // The caller is responsible for the correct (pin → submodule) match
    // (see HW-T41-PINMAP.md §1). Mismatches are caught at runtime —
    // init() asserts the pair is one of the supported ones for ISR
    // dispatch.
    FlexPwmStepper(int stepPin, int dirPin,
                   IMXRT_FLEXPWM_t* pwm, uint8_t submodule, IRQ_NUMBER_t irq);

    // Set up pin modes + install ISR vector. Call once from setup()
    // before any motion call.
    void init();

    // Commanded constant pulse rate, 1..200000 Hz. May be called while
    // running to change speed on the fly (small glitch at the next
    // period boundary as analogWriteFrequency reloads).
    void setSpeed(uint32_t hz);
    uint32_t speed() const { return _speedHz; }

    // Net steps moved since power-on (or last setPosition). Snapshot
    // is taken with interrupts briefly disabled to avoid a torn read.
    long position() const;
    void setPosition(long p);

    // Steps still to go on the active move; 0 when idle or in
    // continuous mode. Signed by direction.
    long distanceToGo() const;

    // True while the pulse train is being emitted.
    bool isRunning() const { return _running; }

    // Kick off a relative move of `n` steps. Sign of n is direction.
    // Replaces any in-flight move. n == 0 is a no-op.
    void moveSteps(long n);

    // Kick off an absolute move to `target`.
    void moveTo(long target);

    // Run an unbounded pulse train; dir = +1 (CW) or −1 (CCW).
    void runContinuous(int dir);

    // Halt pulses immediately (no decel ramp — constant velocity
    // means there's nothing to decelerate). Position is preserved.
    void stop();

    // Internal — called from the static C-style IRQ dispatcher.
    // Don't call this from application code.
    void handleIsr();

private:
    int               _stepPin;
    int               _dirPin;
    IMXRT_FLEXPWM_t*  _pwm;
    uint8_t           _sm;
    IRQ_NUMBER_t      _irq;

    volatile long     _position;
    volatile long     _remaining;
    volatile bool     _running;
    volatile int8_t   _direction;
    uint32_t          _speedHz;

    void _startPulses();
    void _stopPulses();
};
