# PlatformIO pre-build script: regenerate src/build_info.cpp with the build
# time, git revision and environment name (declared in src/build_info.h).
# Runs for every env, native tests included; the file is git-ignored.
import datetime
import pathlib
import subprocess

Import("env")  # noqa: F821 — provided by PlatformIO/SCons

root = pathlib.Path(env["PROJECT_DIR"])


def git(*args):
    try:
        return subprocess.run(["git", *args], cwd=root, capture_output=True, text=True, check=True).stdout.strip()
    except Exception:  # not a checkout, or git missing
        return None


sha = git("rev-parse", "--short", "HEAD") or "nogit"
if sha != "nogit" and git("status", "--porcelain", "--untracked-files=no"):
    sha += "-dirty"
stamp = datetime.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %z")

text = (
    "// Generated by tools/build_info.py before each build — do not edit, not tracked.\n"
    '#include "build_info.h"\n'
    f'const char kBuildStamp[] = "{stamp}";\n'
    f'const char kBuildGit[]   = "{sha}";\n'
    f'const char kBuildEnv[]   = "{env["PIOENV"]}";\n'
)
target = root / "src" / "build_info.cpp"
if not target.exists() or target.read_text() != text:
    target.write_text(text)
